version: "3.8"

services:
  minio:
    restart: unless-stopped
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?err}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?err}
    ports:
      - "9001:9001"
      - "9000:9000"
    networks:
      - inside
  psql:
    restart: unless-stopped
    image: postgres:17.4-alpine3.21
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - inside
    ports:
      - "5433:5432"

volumes:
  postgres-db:
  minio:
networks:
  inside:
